version: "3.8"

services:
  app:
    container_name: wishlist-app-dev
    image: wishlist-app-dev
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - 4000:4000
